README.md
Signed-off-by: Michelle Nguyen <michellenguyen@pixielabs.ai>
=> Add allowInsecureTLS to documentation

README.md
Signed-off-by: Michelle Nguyen <michellenguyen@pixielabs.ai>
=> Add link to Pixie Plugin system docs

README.md
Adding the New Relic plugin to the `Available Plugins` list and other minor updates.
=> Added New Relic plugin

README.md
=> Add a step to the Contributing guide.

plugins/new-relic/plugin.yaml
Signed-off-by: Javier Imbernón <javimb@newrelic.com>
=> Fix NR's logo by using the proper viewbox

plugins/new-relic/plugin.yaml, plugins/new-relic/retention.yaml
Add Kafka latency and bytesPerSecond metrics to New Relic's plugin
=> Add Kafka Metrics

plugins/new-relic/retention.yaml
Tested in the New Relic UI and got the data out.
=> Adding export for Kafka Spans

plugins/new-relic/retention.yaml
=> Add Redis metrics and Spans data to New Relic exports

plugins/new-relic/retention.yaml
=> Add MySQL Metrics.

plugins/new-relic/retention.yaml
=> Update PostgresSQL Spans script to include server-side traces.

plugins/new-relic/retention.yaml
=> Adding DNS Metrics and Spans to Pixie plugin

plugins/new-relic/retention.yaml
=> Add Cassandra Spans and Metrics.

plugins/new-relic/retention.yaml
=> Update MySQL Spans to deduplicate traces, add server-side spans.

plugins/new-relic/plugin.yaml, plugins/new-relic/retention.yaml
=> Cassandra script fixes.

plugins/new-relic/retention.yaml
=> Switch New Relic scripts to enabled by default

plugins/new-relic/retention.yaml
This PR adds the DNS rcode string as a field to make DNS debugging easier.  
I used the DNS rcode strings from [this source](https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-6). Note that this source lists two strings for `rcode==16`, so I used the first option (`BADVERS`). 
Here is a simple PxL script if you want to test out the `dns_rcode_name` function in the Live UI's Scratchpad: 
```
import px
def dns_rcode_name(df, input_col_name, output_col_name):
df[output_col_name] = 'Unknown'
df[output_col_name] = px.select(df[input_col_name]==0, 'NoError', df[output_col_name])
df[output_col_name] = px.select(df[input_col_name]==1, 'FormErr', df[output_col_name])
df[output_col_name] = px.select(df[input_col_name]==2, 'ServFail', df[output_col_name]) …
```
=> Add rcode_name to DNS scripts

plugins/new-relic/plugin.yaml
=> Bump New Relic plugin version.

plugins/new-relic/plugin.yaml
=> Bump version of Plugins

plugins/new-relic/retention.yaml
This PR adds node and deployment metadata to the DNS Span and DNS Metrics export scripts.
=> Add node, deployment metadata to DNS export scripts.

plugins/new-relic/retention.yaml
This PR adds more metadata (node name, deployment name) to the AMQP Span and AMQP Metrics export scripts.
=> Add node, deployment metadata to AMQP export scripts.

plugins/new-relic/retention.yaml
This PR adds more metadata (node name, deployment name) to the Redis Span and Redis Metrics export scripts.
=> Add node, deployment metadata to Redis export scripts.

plugins/new-relic/retention.yaml
Replace Cassandra Opname hack with the built-in one that was added Nov. 10.
=> replace cql_opname hack with px.cql_opcode_name
